### ISSUE TITLE
Warning: incremental compilation (maybe) broken when using `@taylorize` in package

### ISSUE THREAD

**Issue by PerezHz** [PerezHz/TaylorIntegration.jl#106]
When using `@taylorize` inside a module, a warning appears about incremental compilation "maybe" being "fatally broken". I wasn't able to reproduce the problem when defining a module in the REPL, but figured out the following MWE:

I created the [`MyPkg`](https://github.com/PerezHz/MyPkg) julia package, which uses `@taylorize` to define an ODE. Then, `MyPkg` may be `git clone`'d on an empty folder, and from `MyPkg` root dir start a julia REPL and do:
```julia
# first, in an empty folder do:
# git clone https://github.com/PerezHz/MyPkg
# cd MyPkg
# julia ### open a Julia REPL
# then, in the REPL do:
import Pkg
Pkg.activate(".") # activate environment on MyPkg root dir
using MyPkg # warning appears
```
The warning messages that appear are:
```
[ Info: Precompiling MyPkg [87ba5f82-8271-4dfc-8d8f-dcd99beeaf9d]
WARNING: eval into closed module TaylorIntegration:
:-
  ** incremental compilation may be fatally broken for this module **

WARNING: eval into closed module TaylorIntegration:
:^
  ** incremental compilation may be fatally broken for this module **

WARNING: eval into closed module TaylorIntegration:
typeof(MyPkg.xdot2)()
  ** incremental compilation may be fatally broken for this module **

WARNING: eval into closed module TaylorIntegration:
nothing
  ** incremental compilation may be fatally broken for this module **
```

So far, I've reproduced the error on julia 1.3 and 1.4 locally and on a remote machine.

The incremental compilation warnings appear the first time `MyPkg` is loaded via `using MyPkg`, and do not appear on subsequent loadings, until `MyPkg` is changed internally (e.g., by uncommenting the `MyPkg.greet()` function), and `using MyPkg` is ran again so that the code is re-compiled. Also, as far as I can tell, things seem to work fine (`taylorinteg` works fine, etc.) even when the warnings appear, but I don't know if it's safe to live with these warnings hanging around.

A workaround is to set `__precompile__(false)`, but then `MyPkg` is compiled each time it is loaded, and compilation times may become exceptionally slow (~ 10 min) in some cases where the defined ODE involves many operations.

This issue seems to be related to the use of `eval` in the definition of `@taylorize`, and found a [post in Discourse](https://discourse.julialang.org/t/use-of-eval-in-closed-module-and-incremental-compilation-may-be-broken/30028) which dealt with similar things, but wasn't able to figure out a way to get rid of these warnings so that it's possible to not use `__precompile__(false)`. @lbenet, do you know what might be going on here?

**Comment by lbenet** [comment]
I can reproduce the problem, and indeed, it seems it is related to the  use of `eval` in the macro definition. Let  me see what can we do...

**Comment by lbenet** [comment]
This is what I have found so far...

- Regarding the second call to `using MyPkg`, which does not trigger a warning, this is because in Julia (some?) warnings are only triggered once. So this  is expected. If you uncomment the `greet()` definition, precompilation sets-in, and you get again the warning.

- About the warning itself, let's begin stating that inside `MyPkg` you call the macro `@taylorize`. The macro evaluates/creates two new functions: `MyPkg.xdot2(...)` and `MyPkg.TaylorIntegration.jetcoeffs!(::Val{MyPkg.xdot2}, ...)`. Note that the second function is defined within `TaylorIntegration` *module*. I think the warning is then triggered by the fact that `MyPkg.TaylorIntegration` *does not* (or *can not*) accept new methods, becuase it is precompiled.

Once said all this, you can see that things *work* because the two methods that are supposed to be created *are* properly defined:
```julia
julia> methods(MyPkg.xdot2)
# 1 method for generic function "xdot2":
[1] xdot2(x, p, t) in MyPkg at /Users/benet/Fisica/6-JL/MyPkg/src/MyPkg.jl:9

julia> methods(MyPkg.TaylorIntegration.jetcoeffs!)
# 3 methods for generic function "jetcoeffs!":
[1] jetcoeffs!(eqsdiff::Function, t::TaylorSeries.Taylor1{T}, x::TaylorSeries.Taylor1{U}, params) where {T<:Real, U<:Number} in TaylorIntegration at /Users/benet/.julia/dev/TaylorIntegration/src/explicitode.jl:25
[2] jetcoeffs!(eqsdiff!::Function, t::TaylorSeries.Taylor1{T}, x::AbstractArray{TaylorSeries.Taylor1{U},1}, dx::AbstractArray{TaylorSeries.Taylor1{U},1}, xaux::AbstractArray{TaylorSeries.Taylor1{U},1}, params) where {T<:Real, U<:Number} in TaylorIntegration at /Users/benet/.julia/dev/TaylorIntegration/src/explicitode.jl:66
[3] jetcoeffs!(::Val{MyPkg.xdot2}, t::TaylorSeries.Taylor1{_T}, x::TaylorSeries.Taylor1{_S}, p) where {_T<:Real, _S<:Number} in MyPkg
```

A possible (?) way to solve this could be to define the specialized method of `jetcoeffs!` in the calling scope, instead of within `TaylorIntegration`. That is, in `Main` in the usual case, or within `MyPkg` in the present case; but I do not (yet) know how much this can  break things. As a side note, I can get rid of the warning related to `xdot2`, that is, the very last one you are reporting.

**Comment by lbenet** [comment]
For reference: https://github.com/JuliaLang/julia/issues/33416

**Comment by lbenet** [comment]
As far as I have checked, things do work properly; yet, for more involved functions than `xdot2`, the number of warnings becomes unconfortable.  To see that things work, consider
```julia
module MyPkg

# __precompile__(false)

using Reexport
@reexport using TaylorIntegration

greet() = (@show(methods(TaylorIntegration.jetcoeffs!)); nothing)
greet(f) = TaylorIntegration._determine_parsing!(true, f, Taylor1(5), Taylor1(5), nothing)

@taylorize xdot2(x, p, t) = (local b2 = 3; b2-x^2)

end # module
```
Then, you get the warnings but things seem to work:
```julia
julia> using MyPkg
[ Info: Precompiling MyPkg [87ba5f82-8271-4dfc-8d8f-dcd99beeaf9d]
WARNING: eval into closed module TaylorIntegration:
...

julia> MyPkg.greet() # should be 3 methods(!)
methods(TaylorIntegration.jetcoeffs!) = # 3 methods for generic function "jetcoeffs!":
[1] jetcoeffs!(eqsdiff::Function, t::Taylor1{T}, x::Taylor1{U}, params) where {T<:Real, U<:Number} in TaylorIntegration at /Users/benet/.julia/dev/TaylorIntegration/src/explicitode.jl:25
[2] jetcoeffs!(eqsdiff!::Function, t::Taylor1{T}, x::AbstractArray{Taylor1{U},1}, dx::AbstractArray{Taylor1{U},1}, xaux::AbstractArray{Taylor1{U},1}, params) where {T<:Real, U<:Number} in TaylorIntegration at /Users/benet/.julia/dev/TaylorIntegration/src/explicitode.jl:66
[3] jetcoeffs!(::Val{MyPkg.xdot2}, t::Taylor1{_T}, x::Taylor1{_S}, p) where {_T<:Real, _S<:Number} in MyPkg

julia> MyPkg.greet(MyPkg.xdot2) # should return `true`
true
```

Is it an option to use `@taylorize xdot2(...) = ...` outside the module? 

If so, moving *outside* the use of `@taylorize` yields no warning, and using `MyPkg.greet(xdot2)` (note that it lives in `Main`) does return `true`.

**Comment by lbenet** [comment]
Shall I make a PR to get rid of the `evals` inside `@taylorize`?

**Comment by PerezHz** [comment]
Many thanks for looking into this and opening #107 !

> Is it an option to use @taylorize xdot2(...) = ... outside the module?

Do you mean moving the `@taylorize f(...)` statements outside the module? That would be certainly an option! Perhaps we should also document this in the `@taylorize` section in the docs, that if `@taylorize` is used inside a module then these warnings appear, what do you think?

**Comment by lbenet** [comment]
Yes, that's what I mean: `@taylorize` should be used *after* the module, and not inside it. 

I also think it is really a good idea to document this, with the example of `MyPkg`. Incidentally, I am not sure if `Reexport.jl` is truly needed, since then the function (`xdot2` in the discussion) will live in an outer scope; a little more experimentation is needed.

**Comment by lbenet** [comment]
Regarding precompilation, maybe [`SnoopCompile.jl`](https://github.com/timholy/SnoopCompile.jl) is worth checking.

**Comment by PerezHz** [comment]
I found that if `MyPkg` module is defined as posted below (note the `__init__` function with `@taylorize xdot2...` inside):
```julia
module MyPkg

# __precompile__(false)

using TaylorIntegration

greet() = (@show(methods(TaylorIntegration.jetcoeffs!)); nothing)
greet(f) = TaylorIntegration._determine_parsing!(true, f, Taylor1(5), Taylor1(5), nothing)

function __init__()
    myex = :(@taylorize xdot2(x, p, t) = (local b2 = 3; b2-x^2))
    eval(myex)
end

end # module

```
Then, the warnings disappear, although then `xdot2` and the associated `jetcoeffs!` method is re-compiled each time `MyPkg` is loaded. On the other hand, SnoopCompile.jl seems like an interesting thing to try, thanks, I'll check it out!

**Comment by lbenet** [comment]
My understanding is that using `__init__()` will run after the module is loaded, at  run time. See: https://docs.julialang.org/en/v1/manual/modules/index.html#Module-initialization-and-precompilation-1. The warning (topic of this issue) is also mentioned there.

**Comment by PerezHz** [comment]
Update: I obtained a satisfactory solution for my use case by doing the following:

```julia
module MyPkg

# __precompile__(false)

using TaylorIntegration

macro taylorize_mypkg(ex)
    nex = TaylorIntegration._make_parsed_jetcoeffs(ex)
    return quote
        $(esc(ex))
        $(esc(nex))
    end
end

x0 = [1.0, 0.0]
tT = Taylor1(5)
x0T = Taylor1.(x0, tT.order)
dx0T = similar(x0T)
ω = 1.0

@taylorize_mypkg function harm_osc!(dx, x, p, t)
    local ω = p[1]
    local ω2 = ω^2
    dx[1] = x[2]
    dx[2] = - (ω2 * x[1])
    return nothing
end

@taylorize_mypkg xdot2(x, p, t) = (local b2 = 3; b2-x^2)

end # module
```

So instead of using the `TaylorIntegration.@taylorize` macro, I declared a `@taylorize_mypkg` macro inside the `MyPkg` module as shown in the code above. While in Julia 1.4 the warnings still appear, I was able to enable precompiling without any issue. In Julia 1.5, no warnings appear and precompiling works fine.

**Comment by PerezHz** [comment]
Re-opening, since I have a new diagnosis for this issue; will upload a PR in a couple of minutes...

**Comment by PerezHz** [comment]
As discussed in #113, I've traced this issue to a call of `eval` in Espresso.jl, which was affecting `@taylorize` when called inside a module. Besides the precompilation warnings, a really weird hit on performance was observed; these issues seemed unrelated at first, but were part of the same problem...
