### ISSUE TITLE
Install CompatHelper?

### ISSUE THREAD

**Issue by mforets** [PerezHz/TaylorIntegration.jl#122]
CompatHelper.jl helps to keep the `[compat]` entries up-to-date. It automatically makes PRs to update the Project.toml file once installed (instructions [here](https://github.com/JuliaRegistries/CompatHelper.jl#1-installation)).

**Comment by lbenet** [comment]
Thanks for the suggestion!

Would you mind to make a PR on this? That would replace #121 as a long lasting solution, right?

**Comment by mforets** [comment]
sure, i opened https://github.com/PerezHz/TaylorIntegration.jl/pull/123

>  That would replace #121 as a long lasting solution, right?

yes, once it is installed will send PRs to update the comapt bounds of dependencies
