### ISSUE TITLE
Accuracy issues compared to RK-family solvers from OrdinaryDiffEq.jl?

### ISSUE THREAD

**Issue by vram0gh** [PerezHz/TaylorIntegration.jl#133]
I am trying to solve a nonlinear gasdynamics ODE system with high accuracy.  The ODE system does have a `0/0` pole it approaches, and the goal is to be able to use `TaylorIntegration.jl` to approach that pole accurately and robustly.  However, I began by checking the `TaylorIntegration.jl` solution against `Vern7` from `OrdinaryDiffEq.jl` with `abstol=1e-12, reltol=0.0`.  The `Vern7` solver produces good results on the ODE system (as verified through `BigFloat` solutions), so I began by comparing a `Vern7` and `TaylorMethod` solution away from the pole.  However, even with similar or tighter tolerances on the `TaylorMethod` solution, the Euclidean distance between solution points grows to `Order(1e-3)`, so ~9 orders of magnitude higher than the integration tolerance.

I also verified that I am able to get very comparable high-accuracy results between `TaylorIntegration.jl` and `OrdinaryDiffEq.jl` `Vern7` solutions for a nonlinear test ODE system where no subtractive cancellation takes place in the denominators, so I don't believe this to be user error (but I could be wrong/missing something!).

Attached is a `Pluto.jl` notebook, but I will also paste code below.  Note that I tried different values of the method order, and leaving on vs. omitting `parse_eqs` and they didn't seem to ultimately change the magnitude of solution differences.  Again, the `tspan` right-side endpoint prescribed below is still some distance away from the singularity, and the plot shows significant differences building up quite early in the solution trajectory.

```Julia
using OrdinaryDiffEq
using TaylorIntegration
using LinearAlgebra
using Plots

function TMM_odesys!(primes, dependent, params, independent)
    γ = params[1]
    θ = independent
    Mr = dependent[1]
    Mθ = dependent[2]
    gm1o2 = (γ - 1) / 2
    Mθsq = Mθ * Mθ
    Mθsqm1 = Mθsq - 1
    Mθcotθ = Mθ * cot(θ)
    # slightly excessive paretheses, but equations are correct
    primes[1] = ((Mθ * ((gm1o2 * ((Mr * Mr) + (Mr * Mθcotθ))) + Mθsq - 1)) / Mθsqm1)
    primes[2] = (((((gm1o2 * Mθsq) + 1) * (Mr + Mθcotθ)) - (Mr * Mθsqm1)) / Mθsqm1)
    return nothing
end

# Simple Euclidean distance between two points
function solptdiff(u0, u1)
  diff = u0 - u1
  sqrt(dot(diff, diff))
end

cf_test_prob = ODEProblem(TMM_odesys!, [2.5, 0.0], (deg2rad(0.1), 0.4), [1.4])

Vern7sol = solve(cf_test_prob, Vern7(), abstol = 1e-12, reltol = 0.0)

TIsol = solve(cf_test_prob, TaylorMethod(30), abstol = 1e-13, parse_eqs = false)

solptdiff(Vern7sol.u[end], TIsol.u[end]) # On my system, this returns 0.004776986921762344 , much higher than expected

# Next use taylorinteg() to match time points with the Vern7 solution so differences can be compared step-by-step
matching_t_sol = taylorinteg(TMM_odesys!, [2.5, 0.0], Vern7sol.t, 30, 1e-13, [1.4], parse_eqs = false)

# Convenience function to change the returned matrix to a vector of vectors so the difference function can be simply broadcast
function mat2vecvec(m)
  nr = size(m, 1)
  v = Vector{Vector{typeof(m[1,1])}}(undef, nr)
  for i = 1:nr
    v[i] = m[i, :]
  end
  return v
end

matching_t_sol_vv = mat2vecvec(matching_t_sol);

diffs = solptdiff.(Vern7sol.u, matching_t_sol_vv);

# Omit the first point since they are both the IC and the difference is a zero vector which doesn't work with the semilog plotting
plot(Vern7sol.t[2:end], diffs[2:end], yscale = :log10, legend_position = false)
```

[taylorinteg_cf_test.jl.txt](https://github.com/PerezHz/TaylorIntegration.jl/files/7742117/taylorinteg_cf_test.jl.txt)

**Comment by lbenet** [comment]
Thanks for reporting and including code; that truly helps! 

I can indeed reproduce the difference between the solutions as you quoted above. While I need more time to think about the actual issue (singularities should always be taken *very carefully* into account) and the actual comparison, there are two points I think are worth mentioning. First, the `abstol` parameter in TaylorIntegration.jl is a parameter used to compute the time step, which is calculated as explained [here](https://perezhz.github.io/TaylorIntegration.jl/latest/taylor_method/#time-step). Essentially, the last (or one-before-last term) of the Taylor expansion has to be smaller than that `abstol` parameter, which then fixes the time step. So, using the same `abstol` in the two methods is not quite the same. Second, it is better to have a smaller `abstol` if you use Taylor method, and play with the order. As an example, using order 20 and `abstol= 1e-40`, the difference at the end points is reduced to 9.7e-5, which I think it is better in terms of the differences. Yet, I cannot get the `matching_t_sol` for this case...

I need more time to dig into this....

**Comment by vram0gh** [comment]
Hi, thank you for your quick and kind response and also for explaining
how the tolerance parameter is actually used.  I glossed over that as
I was reading the docs and do need to think about this some more.

That being said, I think we agree with the right parameters,
TaylorIntegration should be able to meet or better the results from
the RK-type method.  Please let me know what else I can do to help
debug.

**Comment by lbenet** [comment]
Can you confirm that the following equations are the right ones?

<img src=
"https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0A%5Cdot%7BM_r%7D+%26+%3D++%5Cfrac%7BM_%5Ctheta%5CBig%28+%5Cfrac%7B%5Cgamma-1%7D%7B2%7D+%5Cbig%28M_r%5E2+%2B+M_r+M_%5Ctheta+%5Ccot%28%5Ctheta%29%5Cbig%29+%2B+M_%5Ctheta%5E2-1%5CBig%29%7D%7BM_%5Ctheta%5E2-1%7D%5C%5C%0A%5Cdot%7BM_%5Ctheta%7D+%26+%3D+%5Cfrac%7B%28%5Cfrac%7B%5Cgamma-1%7D%7B2%7D+M_%5Ctheta%5E2%2B1%29%28M_r+%2B+M_%5Ctheta%5Ccot%28%5Ctheta%29%29-M_r%28M_%5Ctheta%5E2-1%29%7D%7BM_%5Ctheta%5E2-1%7D%5C%5C%0A%5Cend%7Balign%2A%7D" 
alt="\begin{align*}
\dot{M_r} & =  \frac{M_\theta\Big( \frac{\gamma-1}{2} \big(M_r^2 + M_r M_\theta \cot(\theta)\big) + M_\theta^2-1\Big)}{M_\theta^2-1}\\
\dot{M_\theta} & = \frac{(\frac{\gamma-1}{2} M_\theta^2+1)(M_r + M_\theta\cot(\theta))-M_r(M_\theta^2-1)}{M_\theta^2-1}\\
\end{align*}">

Is there another way to check the accuracy of the integration? A conserved quantity or so?

**Comment by lbenet** [comment]
Minor tip: I rewrote your equations using `@taylorize` as follows:
```julia
@taylorize function TMM_odesys!(primes, dependent, params, independent)
    local γ = params[1]           # use `local` for constant parameters
    local gm1o2 = (γ - 1) / 2

    θ = independent
    Mr = dependent[1]
    Mθ = dependent[2]
    Mθsq = Mθ^2
    Mθsqm1 = Mθsq - 1
    Mθcotθ = Mθ * cot(θ)
	MrpMθcotθ = Mr + Mθcotθ
    primes[1] = (Mθ * (gm1o2 * (Mr * MrpMθcotθ) + (Mθsq - 1))) / Mθsqm1
    primes[2] = ((((gm1o2 * Mθsq) + 1) * MrpMθcotθ) - (Mr * Mθsqm1)) / Mθsqm1
    return nothing
end
```

This allows you to use `parse_eqs=true` for the Taylor integration, which improves the performance!

**Comment by vram0gh** [comment]
> Can you confirm that the following equations are the right ones?
> 
> ![\begin{align*} \dot{M_r} & = \frac{M_\theta\Big( \frac{\gamma-1}{2} \big(M_r^2 + M_r M_\theta \cot(\theta)\big) + M_\theta^2-1\Big)}{M_\theta^2-1}\\ \dot{M_\theta} & = \frac{(\frac{\gamma-1}{2} M_\theta^2+1)(M_r + M_\theta\cot(\theta))-M_r(M_\theta^2-1)}{M_\theta^2-1}\\ \end{align*}](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0A%5Cdot%7BM_r%7D+%26+%3D++%5Cfrac%7BM_%5Ctheta%5CBig%28+%5Cfrac%7B%5Cgamma-1%7D%7B2%7D+%5Cbig%28M_r%5E2+%2B+M_r+M_%5Ctheta+%5Ccot%28%5Ctheta%29%5Cbig%29+%2B+M_%5Ctheta%5E2-1%5CBig%29%7D%7BM_%5Ctheta%5E2-1%7D%5C%5C%0A%5Cdot%7BM_%5Ctheta%7D+%26+%3D+%5Cfrac%7B%28%5Cfrac%7B%5Cgamma-1%7D%7B2%7D+M_%5Ctheta%5E2%2B1%29%28M_r+%2B+M_%5Ctheta%5Ccot%28%5Ctheta%29%29-M_r%28M_%5Ctheta%5E2-1%29%7D%7BM_%5Ctheta%5E2-1%7D%5C%5C%0A%5Cend%7Balign%2A%7D)
> 
> Is there another way to check the accuracy of the integration? A conserved quantity or so?

Yes, I can confirm the equations are correct as you've captured them.  Unfortunately, there is no conserved quantity at each timestep that can be used to cross-check a given solution point; the only way I have been able to come up with is to use other numerical solutions.  This can be done with `BigFloat` solutions, and there are also alternate ODE formulations for the same physical scenario which should yield equivalent answers, but it would still be a matter of comparing numerical solutions.

Before trying `TaylorIntegration.jl`, I tried a large portion of the non-stiff solvers in the `DifferentialEquations.jl` suite and found `Vern7` to do the best in terms of accuracy (compared to 256-bit `BigFloat` with `RK4`) near singular points, with all methods doing pretty well at tight tolerances when away from the singularity (like `abs(Mθsqm1) > 1e-2`) .

Thanks also for the cleaned-up version of the ODE system - I pulled this out of a module I'd written, so didn't think to use the `local` scope declarations (`local` should only be necessary when the code is run at the toplevel/REPL, correct?).

**Comment by lbenet** [comment]
For reference, throw a remarkable job of @vram0gh we found out that the precision problem is related with a a bug in the implementation of `tan` and `tan!` in TaylorSeries.jl, which was fixed in https://github.com/JuliaDiff/TaylorSeries.jl/pull/297.

I'm leaving this open for testing further that this has indeed been solved.

**Comment by vram0gh** [comment]
@lbenet : Thank you very much for fixes and updates!!

I just ran the testcase provided in the initial post, with the following changes:

- Used your `@taylorized` rewrite of the ODE function
- Omitted `parse_eqs` argument in `TaylorMethod` solve
- Specified `abstol = 1e-20` for `TaylorMethod`

The difference between the two solutions was `~4e-13`, with 27 integration steps from `TaylorMethod` vs. 51 from `Vern7`.

I think we are good to close this issue and will do so.
