### ISSUE TITLE
Taylorize system dynamics with control inputs

### ISSUE THREAD

**Issue by ga72kud** [PerezHz/TaylorIntegration.jl#135]
Thank you for this great package. I was wondering if it possible to extend the functionality to systems with control input. 

Is it possible to use `@taylorize `with 
```julia
x_n=f(x,u,t)
```

**Comment by lbenet** [comment]
Hi! Thanks for reaching out. Can you be more explicit what do you mean by `x_n=f(x,u,t)`? Sorry, not a control expert...

**Comment by ga72kud** [comment]
Thank you for programming the package. Oh, I see. Maybe then it will be a bit difficult to find a solution. I do not know how much it is implemented and how much effort it would mean to use the taylorize function for nonlinear systems with control inputs.
x_n=f(x(t),u(t))
x(t) the system state, u(t) the control input for controlling the state. The control state and control input are time dependent.

MathematicalSystems.BlackBoxControlContinuousSystem at https://juliareach.github.io/MathematicalSystems.jl/latest/lib/types/#MathematicalSystems.LinearControlContinuousSystem

**Comment by lbenet** [comment]
Sorry for the long silence...

What `@taylorize` does (be aware of incoming changes #137) is to generate an internal specialized method of (the internal function) `jetcoeffs!`, to optimize the number of operations and allocations. The function `jetcoeffs!` is where the Taylor method is implemented, and it *updates* the Taylor series of the dependent variables `x(t)`. This boils down to compute, step by step, all required Taylor coefficients of a given order, and iterate that until the maximum order. 

You can have your own functions (e.g., `mycontrol(...)` or `u(t)`) inside the equations of motion, which `@taylorize` *copies* as it is, if it does not recognize it as a "simple" (recognized mathematical such as `sin` or `exp`) function. This means that `@taylorize` will not optimize it. A possibility to incorporate the control function so `@taylorize` parses it, is to write it plainly within the function which defines the equations of motion. I'm not sure if this makes sense or not for a control system, though. This implicitly  assumes that the control is updated/affects each order of the Taylor expansions... (I hope this makes sense.)

If you could provide a minimal working example, maybe the simplest textbook example, I may have a playground to propose something.

I hope these comments are helpful.

**Comment by ga72kud** [comment]
Maybe we can have the starting point with an example from your documentation, with a new pendulum_with_control function:

```julia
using TaylorIntegration


@taylorize function pendulum!(dx, x, p, t)
    dx[1] = x[2]
    dx[2] = -sin(x[1])
    return dx
end

@taylorize function pendulum_with_control!(dx, x, u, p, t)
    dx[1] = x[2]
    dx[2] = -sin(x[1])+u
    return dx
end


# Initial time (t0), final time (tf) and initial condition (q0)
t0 = 0.0
tf = 100.0
q0 = [1.3, 0.0]

t2, x2 = taylorinteg(pendulum!, q0, t0, tf, 25, 1e-20, maxsteps=1500);

```

**Comment by lbenet** [comment]
Thanks for bringing this example! 

First the error: the error occurs because `@taylorize` expects a function with arguments `(du, u, p, t)`, and  `pendulum_with_control!` has a fifth parameter. This is because we follow the convention used in DifferentialEquations (with less flexibility).

The question is what is `u` in the code? If it is a value (e.g., `u = -3.2`) then you may pass it as a parameter `p`, e.g.:
```julia
@taylorize function pendulum_with_control!(dx, x, p, t)
    local u = p # local avoids to convert it into a Taylor1 object
    dx[1] = x[2]
    dx[2] = -sin(x[1])+u
    return dx
end
```

If you would like to have `u` being a function, you could try the following:
```julia
@taylorize function pendulum_with_control!(dx, x, p, t)
    u = my_control_function(x,t)
    dx[1] = x[2]
    dx[2] = -sin(x[1])+u
    return dx
end
```
`@taylorize` should be able to parse the last form, though it may not optimize it.

**Comment by ga72kud** [comment]
Hi, here is the code. The last example could also be used for both cases if my_control_function returns a constant value. I have to verify the following code and the actual control law makes no sense. But this is an example where I can start with. Thank you for the nice Julia package. I will continue and start a new issue if there are further problems. Thank you. 
```julia
using TaylorIntegration
using Plots
function my_control_function(x,t)
    return -4.#sin(x[1])+cos(t)
end

@taylorize function pendulum_with_control!(dx, x, p, t)
    u = my_control_function(x,t)
    dx[1] = x[2]
    dx[2] = -sin(x[1])+u
    return dx
end


# Initial time (t0), final time (tf) and initial condition (q0)
t0 = 0.0
tf = 100.0
q0 = [0.0, 0.0]

t2, x2 = taylorinteg(pendulum_with_control!, q0, t0, tf, 25, 1e-20, maxsteps=1500);
plot(x2[:,1], x2[:,2])


```

**Comment by lbenet** [comment]
Excellent that you have a starting point to work with this. Please, do open issues if you need more assistance.
