### ISSUE TITLE
Update to TaylorSeries v0.12

### ISSUE THREAD

**Issue by schillic** [PerezHz/TaylorIntegration.jl#139]
You probably also want to enable `CompatHelper` again ([here](https://github.com/PerezHz/TaylorIntegration.jl/actions/workflows/CompatHelper.yml)).

**Comment by schillic** [comment]
Would be nice to make a new release with the fix. Thanks!

**Comment by lbenet** [comment]
Sorry for the delay., it's been a busy day... it's on its way now.

**Comment by schillic** [comment]
Sure, I just wanted to check that you did not forget it :+1:
