### ISSUE TITLE
Conditional output size and @taylorize?

### ISSUE THREAD

**Issue by vram0gh** [PerezHz/TaylorIntegration.jl#140]
I have an ODE system that can include or exclude an equation depending on how the the solution is being used.

We know input vector length is not a part of the type signature without using something like `StaticArrays.jl`.  So for `DifferentialEquations.jl` ODEs, I check the length of the input vector to determine if the additional component is included.  Within an `if` block, I compute the augmenting ODE RHS if the input vector contains that dependent variable.

Currently with `@taylorize`, wrapping the computation in an `if` guard in the original function definition doesn't prevent the generated code from always attempting to access the additional input element, which may not exist.

What is the best approach for handling this situation when using `TaylorIntegration.jl`?  The options seem to be:

- Have two ODE functions with different names: one with the additional equation, one without.  If I do this and still want both functions to be optimized by `@taylorize`, what is the proper way to avoid literal duplication of the common computations into both functions, or overhead from unnecessary copies/allocations/function calls?
- Use `StaticArrays.jl` to have two different methods for the same name, one with the extra component, one without.  If going this route, again, what is the best way to share the common code in a way that works well with `@taylorize`?
- Feature request that `@taylorize` recognize the conditional guard on the computation and output of additional variables.

Am I missing an obvious or easy option?  What is the recommended approach?  Apologies if opening this issue is not the right way to go about this.

**Comment by lbenet** [comment]
Thanks for opening this. I would have (naively) though that it would work with an `if` statement of the form:
```julia
function myeqs(du, u, params, t)
    # Some code 
    if length(du) == 5 # 5 is an arbitrary example
        du[5] = ...
    end
    return du
end
```

I can't check this right now, but I will try to get back to it later. If you can provide us with a minimum (non-)working example, this could speed things up...

**Comment by vram0gh** [comment]
Thank you; here is a simple example:

```julia
@taylorize function var_simpletest!(primes, dependent, params, independent)
  x = independent
  y = dependent[1]
  primes[1] = ((y * sin(x))^2) / (x * y)
  if (length(dependent) > 1)
    r = dependent[2]
    primes[2] = r * primes[1]
  end
  return nothing
end

function Taylor_poly_var_simpletest()
  ord = 20
  x = Taylor1(Float64, ord)
  x[0] = 1.0
  y = [Taylor1(2.0, ord)]
  yprime_out = [Taylor1(0.0, ord)]
  TaylorIntegration.jetcoeffs!(Val(var_simpletest!), x, y, yprime_out, [])
  return y
end
```

REPL trace:

```julia
julia> Taylor_poly_var_simpletest()
ERROR: BoundsError: attempt to access 1-element Vector{Taylor1{Float64}} at index [2]
Stacktrace:
 [1] getindex
   @ ./array.jl:805 [inlined]
 [2] jetcoeffs!(#unused#::Val{var_simpletest!}, independent::Taylor1{Float64}, dependent::Vector{Taylor1{Float64}}, primes::Vector{Taylor1{Float64}}, params::Vector{Any})
   @ Main ./none:0
 [3] Taylor_poly_var_simpletest()
   @ Main ./REPL[6]:7
 [4] top-level scope
   @ REPL[7]:1
```

**Comment by lbenet** [comment]
I see... I think the problem is that `@taylorize` *guesses* the number of components (of the internal vectors) and it seems it's doing it wrong in this example. 

Have you tried to define the extended system (with a trivial equation, e.g. `du[2] = zero(u[1])`) when there is no guard, and otherwise *change* that equation as you need?

**Comment by lbenet** [comment]
Another possibility is that you pass the length as a parameter in the function call. You can see an example in the tests [here](https://github.com/PerezHz/TaylorIntegration.jl/blob/419c6d60a0d96d6ef7d8d20c42793dabefcb3814/test/taylorize.jl#L444).

**Comment by vram0gh** [comment]
Those are both good points.  I was focused on keeping the behavior implicit so that I missed these options.

For my ODE, it happens to be the case that if the component is set to zero, it will inherently leave the output as zero.  For the generic case, if the computation is to be done conditionally, writing the test in the `if` must be done with something like `iszero` instead of naive comparisons.

It seems like the implicit output adjustment is atypical, so I understand if it's not a use-case that you would wish to support in `@taylorize`.  If that is the decision, then perhaps the documentation could be updated to indicate this is unsupported and to point out these explicit alternatives.  If so, I'd be willing to take a shot at a documentation patch.

**Comment by lbenet** [comment]
Thanks a lot ! Yes, please, submit a patch for the docs! We are always open for improvements!

**Comment by vram0gh** [comment]
Thanks for the discussion on the topic!  With the doc updates now merged, I'll close.
