### ISSUE TITLE
`ODEProblem`s with `recompile=false` flag not supported

### ISSUE THREAD

**Issue by nathanaelbosch** [PerezHz/TaylorIntegration.jl#149]
One way to reduce additional recompilations is to construct the ODE problem with `ODEProblem{true,false}(...)`. This is currently not supported by TaylorIntegration.jl, but it would be great to have this.

Minimal example:
```julia
using OrdinaryDiffEq, TaylorIntegration
function lorenz(du, u, p, t)
    du[1] = 10.0(u[2] - u[1])
    du[2] = u[1] * (28.0 - u[3]) - u[2]
    du[3] = u[1] * u[2] - (8 / 3) * u[3]
    return nothing
end
prob = ODEProblem{true,false}(lorenz, [1.0; 0.0; 0.0], (0.0, 1.0))
solve(prob, TaylorMethod(25))
```

I also observed that `TaylorIntegration.jetcoeffs!` fails when `f` comes from the problem definitions above. 

EDIT: Fixed typos in the minimal example and added "using OrdinaryDiffEq" for completeness.

**Comment by lbenet** [comment]
Hi! Thanks for drawing our attention to this problem. 

I think it is fair to say that we are a bit behind in everything related to provide a fully functional common interface with DifferentialEquations.jl. Today it is a bit complicated for me to have a look on this, but I will try to find some time the next few days.

Once said this, I think I should mention [`@taylorize`](https://perezhz.github.io/TaylorIntegration.jl/latest/taylorize/) as a way to optimize allocations and runtime in the code, which somewhat deals with the peculiarities of Taylor's integration method.

**Comment by nathanaelbosch** [comment]
I see, thanks for the reply. To be fair, I do not actually ever use the DifferentialEquations.jl interface, I only came by the issue because I rely on `jetcoeffs!` to initialize the ODE solvers in ProbNumDiffEq.jl ([code here](https://github.com/nathanaelbosch/ProbNumDiffEq.jl/blob/42e58bba71af26ce0d7ce90a8da2e32def42cadf/src/initialization/taylormode.jl#L31-L45)), and following some recent discussion about reducing compilations by using `ODEProblem{true,false}` I wanted to get similar results in ProbNumDiffEq.jl. In any case, thanks a lot for having a look!

**Comment by lbenet** [comment]
I'll try to have a look on your use case during this weeks. If you can provide a link to the discussion you mention about using `ODEProblem{true,false}`, that will be helpful!

**Comment by nathanaelbosch** [comment]
`ODEProblem{true,false}` just became the new default (https://github.com/SciML/SciMLBase.jl/releases/tag/v1.51.0) - I think this just broke the examples in your documentation :/ To use your solvers as before (without figuring out how to support `ODEProblem{true,false}`) you could adjust the examples to explicitly build `ODEProblem{true,true}` (for problems with in-place formulation).

Unfortunately I don't really know of a good documentation of these things. There was a bit of a dicussion in [one of my commits](https://github.com/nathanaelbosch/ProbNumDiffEq.jl/commit/135c4155f61efd23f2cd896c5a5517909262b501#comments), but in general I just saw some discussions on slack#diffeq-bridged.

Pinging @ChrisRackauckas in case he has some input on what should be done.

**Comment by nathanaelbosch** [comment]
Regarding my specific usecase: Before passing `f` to `TaylorIntegration.jetcoeffs!` I now do 
```julia
if f.f isa SciMLBase.FunctionWrappersWrappers.FunctionWrappersWrapper
    f = ODEFunction(SciMLBase.unwrapped_f(f), mass_matrix=f.mass_matrix)
end
```
which fixes the main issue I had.

**Comment by ChrisRackauckas** [comment]
This library probably wants to just explicitly unwrap like that.

**Comment by ChrisRackauckas** [comment]
We should get an FAQ written up. Though I'm adding a fallback so the error will actually go away soon. But library writers probably still want to specialize in some cases.

**Comment by lbenet** [comment]
Thanks @ChrisRackauckas from joining our discussion; during the next few days I have some time (no lectures) so I'll try to upgrade the dependencies and solve the issues around. I guess we are among those developers who want to specialize the most common cases. 

Can you please tell me what are the minimum versions we may require (we currently use DiffEqBase.jl and OrdinaryDiffEq.jl), so the errors pop out? Do we also need to require SciMLBase?

**Comment by ChrisRackauckas** [comment]
You probably want to just `SciMLBase.unwrapped_f(prob.f)` at the top of the solve for this package, and require SciMLBase v1.51.0 minimum.

**Comment by nathanaelbosch** [comment]
I was about to fix this, but when I ran the original example again the error does not appear anymore. I'm a bit unsure why?

In any case, I'm closing the issue since there is no error.
