### ISSUE TITLE
UndefVarError occurs when calling _allocate_jetcoeffs!

### ISSUE THREAD

**Issue by vram0gh** [PerezHz/TaylorIntegration.jl#153]
I just restarted use of `TaylorIntegration.jl` following #137 becoming a part of the released version.  I'm not sure if the below is a bug in the current `@taylorize` or a misuse on my part:

```julia
using TaylorIntegration

@taylorize function odesys_test!(primes, dependent, params, independent)
    local p1 = params[1]
    local p1m1 = (p1 - 1)
    local u1_scalefactor = params[2]
    local u2_scalefactor = params[3]
    θ = independent
    u1 = dependent[1] * u1_scalefactor
    u2 = dependent[2] * u2_scalefactor
    u1sq = u1 ^ 2
    u2sq = u2 ^ 2
    T = (1 - u1sq) - u2sq
    primes[1] = u2 / u1_scalefactor
    primes[2] = (((u1 * u2sq) - (p1m1 * ((2 * u1) + (u2 * cot(θ))) * T)) / ((p1m1 * T) - u2sq)) / u2_scalefactor
  end
```

REPL output, Julia 1.8.2, TaylorIntegration.jl 0.10.0
```julia
julia> order = 10
julia> t_start = 1.75
julia> t_Taylor = Taylor1(t_start, order)
julia> IVs = [0.18, 2.1]
julia> dependent_Taylor=Taylor1.(IVs, order)
julia> primes_Taylor = deepcopy(dependent_Taylor)
julia> TaylorIntegration._allocate_jetcoeffs!(Val(odesys_test!), t_Taylor, dependent_Taylor, primes_Taylor, [1.2, 1.0, 1.0])
ERROR: UndefVarError: tmp789 not defined
Stacktrace:
 [1] _allocate_jetcoeffs!(#unused#::Val{odesys_test!}, independent::Taylor1{Float64}, dependent::Vector{Taylor1{Float64}}, primes::Vector{Taylor1{Float64}}, params::Vector{Float64})
   @ Main ./none:0
 [2] top-level scope
   @ REPL[32]:1
```

My use case is having TaylorIntegration.jl generate the jet of coefficients, but using these coefficients for other purposes.  With the prior version of `_jetcoeffs!`, I was able to accomplish this without issue.

`_allocate_jetcoeffs!` does work for a simpler example:
```julia
@taylorize function odesys_test2!(primes, dependent, params, independent)
  local p1 = params[1]
  local p2 = params[2]
  local p3 = params[3]
  θ = independent
  u1 = dependent[1]
  u2 = dependent[2]
  u1sq = u1 ^ 2
  u2sq = u2 ^ 2
  primes[1] = u2 / p2
  primes[2] = (((u1 * u2sq) - p1) * cot(θ)) / p3
end
```

REPL:
```julia
julia> TaylorIntegration._allocate_jetcoeffs!(Val(odesys_test2!), θ_Taylor, dependent_Taylor, primes_Taylor, [1.4, 1.0, 1.0])
(Taylor1{Float64}[ 0.7938 + 𝒪(t¹¹),  - 0.6062 + 𝒪(t¹¹),  - 0.18114695257159807 + 𝒪(t¹¹),  0.10981128264890275 + 𝒪(t¹¹),  1.75 + 𝒪(t¹¹),  0.18 + 𝒪(t¹¹),  2.1 + 𝒪(t¹¹),  0.0324 + 𝒪(t¹¹),  4.41 + 𝒪(t¹¹)], Vector{Taylor1{Float64}}[[]])
```

Also, now that `tmpTaylor` and `arrTaylor` are preallocated, it would be very helpful if the documentation were updated to explain their relationship to the internal API.  For example, the `@taylorize` documentation shows the code generated for the pendulum problem.  But do the values stored in `tmpTaylor` and `arrTaylor` at entry into `_jetcoeffs!` matter, other than having the right type, shape, and order?  The example `_jetcoeffs!` suggests it doesn't, yet the example `_allocate_jetcoeffs!` seems to go to some length to not just initialize `tmpTaylor` and `arrTaylor` to zero.

**Comment by lbenet** [comment]
Thanks for reporting, I will have a look during the day. As a side note, this is maybe related to #146 (#143), but at the moment I am not sure...

Also, thanks for your suggestion to better explain `@taylorize` and its internals in the docs. I'll work on that too; I'm currently looking for inconsistencies that I didn't noticed before. 

If you want to experiment with the two version to find the inconsistency, you can do the following:
```julia
julia> ex = :(
function odesys_test2!(primes, dependent, params, independent)
  local p1 = params[1]
  local p2 = params[2]
  local p3 = params[3]
  θ = independent
  u1 = dependent[1]
  u2 = dependent[2]
  u1sq = u1 ^ 2
  u2sq = u2 ^ 2
  primes[1] = u2 / p2
  primes[2] = (((u1 * u2sq) - p1) * cot(θ)) / p3
end);

julia> TaylorIntegration._make_parsed_jetcoeffs(ex)
```
The output of the last command is different in v0.8.11, returning one single function (`jetcoeffs!`), and v0.9 (and later) returning two functions (`jetcoeffs!` and `_allocate_jetcoeffs!`), both non exported.

**Comment by lbenet** [comment]
A work around for now: 
```julia
@taylorize function odesys_test2!(primes, dependent, params, θ)
  local p1 = params[1]
  local p2 = params[2]
  local p3 = params[3]
  # θ = independent
  u1 = dependent[1]
  u2 = dependent[2]
  u1sq = u1 ^ 2
  u2sq = u2 ^ 2
  primes[1] = u2 / p2
  primes[2] = (((u1 * u2sq) - p1) * cot(θ)) / p3
end
```
It seems that something breaks down when the independent variable is redefined.

**Comment by lbenet** [comment]
I'm glad the comment was helpful.
