### ISSUE TITLE
Backwards integration

### ISSUE THREAD

**Issue by blas-ko** [PerezHz/TaylorIntegration.jl#37]
Right now, it's not possible to integrate ODEs backwards. I know it's that way by design, but why is it that way? 
Sometimes it's practical to integrate "to the past" and I think it would be a nice feature to have. 
I found this by trying to do a Newton's method around an specific time.

**Comment by PerezHz** [comment]
Sure, that's a case that actually hasn't been implemented, and actually there's no reason *why* we haven't done it! But at the same time it shouldn't be much of a trouble to do: if we want to integrate from `t0` to `tmax` with `t0>tmax` I guess a lazy way to do it would be to define, outside `taylorinteg`, `u0=-t0`, `umax=-tmax`, and then integrate from the initial time `u0` through the final time `umax`. As always, we are happy to receive contributions, so if you have some concrete ideas in mind to implement this, please go ahead and submit a PR!

By the way, I don't know if the following is related, but it sounds like it is: there's a trick which @lbenet taught me related to root-finding with Newton's method while performing Taylor integration for a given problem. The essential idea is that, for a given surface `g(t, x, dx)` (`x` is the dependent variable, either a scalar or a vector, and `dx` is the time-derivative of `x`) for which you'd like to test surface crossings, you don't actually need to "re-integrate" the solution while getting the iterates for Newton's method, but a single Taylor expansion near the crossing is sufficient. Let's say that you found there's a crossing through the surface `g` between times `t0` and `t1`, and that you have the Taylor expansion `x(t1)` of the dependent variable `x` at time `t1`. Then, using this expansion, you can evaluate `g1 = g(t, x, dx)(t1)` as well as the time-derivative of g at `t1`, `dg1=derivative(g(t, x, dx))(t1)`. Using these values you can actually compute the first iterate of your Newton process `tnr=t1-g1/dg1`, and iterating this process, you can actually find "a" root of `g` between `t0` and `t1` (there are some technical caveats regarding the unicity of that root within `t0` and `t1`, but that's another story). This way, you avoid the need to integrate, sometimes backwards, sometimes forward, while iterating the Newton process.

Still, backwards integration is a nice feature to have! So, again, please go ahead!

As a side note: I have some hand-crafted stuff related to surface intersections, where I use some Newton's method stuff, at the `jp/surface-intersections` branch, which may (or may not) be useful for your use case. There, I have been playing with the ideas I described in the last paragraph. I even have some root-finding examples included in the `test` folder for that branch. It's even possible to do root-finding for jet transport problems, or even to find roots of high-order derivatives of the surface function `g`! Feel free to check out that branch! I suspect it might be ready to submit a PR, but I'd like to test it a bit more before PR-ing. If there's any other way that we may help you, please let us know!

**Comment by blas-ko** [comment]
@PerezHz this sounds excellent! I'm checking this out for sure! 

I think I'll be making the PR nevertheless as it's a nice feature to have and it's easy to implement.
Thanks a lot!

**Comment by blas-ko** [comment]
I've been checking your `jp/surface-intersections` branch and it has been really helpful! I've just done really simple examples (such as pendulum or spirals or centers) and it's working without problems! I have some comments and additions that I'll like to discuss with you about this branch! How should this be done? An issue? PR?

**Comment by PerezHz** [comment]
Glad that this is being helpful @blas-ko! Just opened #38, where we can continue discussion about this

**Comment by PerezHz** [comment]
> I think I'll be making the PR nevertheless as it's a nice feature to have and it's easy to implement.

One should be particularly careful when dealing with non-conservative equations of motion! For example, think about the driven, damped linear oscillator for a given initial condition `q0=[x0,y0]`:

```julia
#the driven, damped linear oscillator ODE:
function drivdamposc!(t, x, dx)
    dx[1] = x[2]
    dx[2] = -λ*dx[1]-(ω^2)*x[1]+ϵ*cos(Ω*t) # `-λ*dx[1]` represents the dissipative term, λ>0
    nothing
end
```

When integrating this backwards in time, the user either should do `λ=-λ` and then integrate the problem above with the initial condition `qf=[xf,-yf]`, where `xf`,`yf` represent the last value of the forward integration (easy, but requires an action by the user); or else, to be done automatically, without further action by the user, inside the backwards `taylorinteg` we should invert the appropriate components of the initial condition, and construct a new ODE function with inverted signs for appropriate terms:

```julia
#the driven, damped linear oscillator ODE:
function drivdamposc_bw!(t, x, dx)
    dx[1] = x[2]
    dx[2] = λ*dx[1]-(ω^2)*x[1]+ϵ*cos(Ω*t) # note the inverted sign for the dissipative term
    nothing
end
```

**Comment by PerezHz** [comment]
Or perhaps there is an easier way? My point is, one should be careful when integrating backwards
