### ISSUE TITLE
Towards v0.0

### ISSUE THREAD

**Issue by lbenet** [PerezHz/TaylorIntegration.jl#4]
(This is a copy of the list that appeared originally in #3)
To do's before creating the v0.0 tag commit. Main changes are:

- [x] Choose a suitable license, and add it into `LICENSE.md` #3
- [x] Add `.travis.yml` #3
- [x] Update jupyter notebooks found in examples/
- [ ] Add details to `README.md`; in particular links to concrete examples. To be discussed: include in `README.md` a fast, easy example for users who need to use the package right away.
- [ ] Documentation

**Comment by lbenet** [comment]
I think that what we have now is ok to tag a first version. What do you think @PerezHz ?

**Comment by PerezHz** [comment]
I agree @lbenet ! Actually I have already tagged the last commit (0b095efa8dbe54913d01628ca24b83eae579908c) as v0.0.1, and submitted a PR to METADATA.jl (see [here](https://github.com/JuliaLang/METADATA.jl/pull/6429)) to officially register  this package! Maybe we can close this issue and save the documentation for v0.0.2?

**Comment by lbenet** [comment]
Closing, following your proposal.
