### ISSUE TITLE
Assertion error t1 > t0 where it shouldn't

### ISSUE THREAD

**Issue by blas-ko** [PerezHz/TaylorIntegration.jl#45]
I'm working in a 3-body problem and I got to the following situation where for **some** initial conditions (In particular `[0,0]`) an `Assertion Error` is thrown. 
```julia
using TaylorSeries, TaylorIntegration

R_1 = -0.37037037037037035
R_2 = 9.62962962962963
Ω  = 0.16431676725154984
M_1 = 26.0
M_2 = 1.0

function test!(t,x,dx)
   
    r_13_cubed = ( (x[1]-R_1)^2 + x[2]^2 )^(3/2)
    r_23_cubed = ( (x[1]-R_2)^2 + x[2]^2 )^(3/2)
    
    dx[1] = -( M_1*(x[1]-R_1)/r_13_cubed + M_2*(x[1]-R_2)/r_23_cubed ) + Ω*(Ω*x[1])
    dx[2] = (-M_1/r_13_cubed -M_2/r_23_cubed + Ω^2)*x[2] 
    
    nothing
end

ord_taylor = 28
abstol = 1.0e-20

q0 = [0.0,0.0]
t0 = 0.0
tmax = 10
tv = linspace(t0,tmax,tmax*10)

taylorinteg(test!, q0, tv, ord_taylor, abstol);

AssertionError: t1 > t0
```
I tried simplifying the equations of motion but it seems that this error is sensitive to initial conditions and constants parameters also. Note that `q0 = [0,0]` doesn't blow up or anything... 

Any ideas of what could be happening?

**Comment by lbenet** [comment]
I am not sure what is happening, but I think `q0` leads to a a collision with one of the singularities. When you approach it, the kinetic energy goes up, and the step-size tends to zero. I think the error is precisely showing that the step-size is zero.

I've rerun your code but using `taylorinteg(test!, q0, 0.0, 10.0*tmax, ord_taylor, abstol, maxsteps=100);` and it completes without any problem. Yet, you can see that the solution is sort of stuck at a small value of time, which would be consistent with a collision with M_1.

**Comment by blas-ko** [comment]
Yes, I think this is indeed because of the divergence of the kinetic energy of the problem due to the singularity. 
Thanks!
