### ISSUE TITLE
Compatibility with DiffEqs

### ISSUE THREAD

**Issue by lbenet** [PerezHz/TaylorIntegration.jl#46]
Important changes are coming or in-process in JuliaDiffEq, as it has been [recently announced](http://juliadiffeq.org/2018/01/24/Parameters.html)). So I am opening this issue to discuss how to approach that, in view of the possibility of using TaylorIntegration from JuliaDiffEqs (#44) .

Possibilities are: 
1. adapt the convention used for the definition of the equations of motion; currently we use the forms `f(t,u)` or `f!(t,u,du)`; 
2. pin the version of DiffEqs used (to v3.1.0);
3. adapt the call from JuliaDiffEqs, such that `f(u,p,t) --> f(t,u)` or `f(du,u,p,t) --> f!(t, u, du)`; 
4. something else. 

From those options, I prefer the 3rd option though the 1st one could be a longer-term solution. (I simply like the convention independent and dependent/mutating variables in that order, but this is not the point.) In any case, I think we will need to use some sort of anonymous functions trick to get around the parameters, e.g., by using `(du,u,t) -> f(du,u,p,t)` in the function field.

@ChrisRackauckas Would that suffice?

**Comment by ChrisRackauckas** [comment]
Yeah, that would suffice. That anonymous function compiles and inlines the change so it doesn't have a performance problem either. I'd do that fix for now, and then you can take all the time you want for a longer term solution.

**Comment by lbenet** [comment]
Thank you!

We have also noticed some issues with the tests in Julia 0.7, some which we have traced to some dependencies of DiffEqs. Do you have any advice on them?

**Comment by ChrisRackauckas** [comment]
StaticArrays is broken on v0.7 right now which is causing issues there. I am not sure what to do about that other than wait.

**Comment by lbenet** [comment]
Thanks @ChrisRackauckas for implementing this in #49. I am closing this issue
