### ISSUE TITLE
Documentation for v0.8 was not built

### ISSUE THREAD

**Issue by lbenet** [PerezHz/TaylorIntegration.jl#94]
The problem seems to have been discussed already [here](https://discourse.julialang.org/t/travis-ci-configuration-breaking-changes/34268).

**Comment by PerezHz** [comment]
I was able to re-trigger from travis the docs build for v0.8.0 and now the docs corresponding to that version are available. The fix proposed in the link you posted did work here, thanks! I can push to the master branch the changes to the travis config, to have this fixed for the time being. Although, the Poincaré maps section seems to have a lot of output from the animations...

**Comment by lbenet** [comment]
Thanks for taking a look on this. I see your point: the figures in the Poincaré maps section didn't appear as they should have. Did you build the docs manually? I checked them locally and it worked.

Another question: did you follow the indications on the link provided above, and changed travis.yml? I guess this is the way to solve the issue (for a *longer* term).

**Comment by PerezHz** [comment]
> Did you build the docs manually? I checked them locally and it worked.

I built the docs via travis.

> Another question: did you follow the indications on the link provided above, and changed travis.yml? I guess this is the way to solve the issue (for a longer term).

I followed the indications from the link and pushed the changes in .travis.yml to the branch `jp/fixtravis`. Then, on travis, I just re-triggered the build for the `dev` docs and the stable (i.e., `v0.8.0`) docs. If you think the changes as they are now look good, then I can push those changes to master.

**Comment by lbenet** [comment]
Let's see if retriggering travis again solves things. In any case, I'm in favor of having this in master. I think if you open a PR we can see if there are any problems in the docs build process.

**Comment by lbenet** [comment]
Mmmm...., though it may not build v0.8 of the docs...

**Comment by PerezHz** [comment]
Just opened #95 to see if the new travis configuration builds the docs correctly at least for master (things seem OK so far). Regarding v0.8.0, I was able to build the v0.8.0 docs from travis and that's the version to which the "stable" link points in the README.

**Comment by PerezHz** [comment]
Closed by #95
